---
image: jembi/go-cli-test-image
defaultTargetLauncher: docker
disableKubernetes: false
disableIG: false
disableCustomTargetSelection: false
packages:
  - id: example
    name: Example package
  - id: example-2
    name: Another example package
