---
image: 'jembi/go-cli-test-image'
logPath: /tmp/logs

packages:
  - core
  - client
  - dashboard-visualiser-jsreport

customPackages:
  - id: disi-on-platform
    path: "git@github.com:jembi/disi-on-platform.git"

profiles:
  - name: dev
    packages:
      - core
      - client

    envFiles:
      - ./features/test-conf/.env.test
    dev: true

  - name: profile-2
    packages:
      - core
      - disi-on-platform
    customPackages:
      - id: disi-on-platform
        path: "git@github.com:jembi/disi-on-platform.git"
    envFiles:
      - ./features/test-conf/.env.test
    dev: false
