---
image: 'jembi/go-cli-test-image'
logPath: /tmp/logs

packages:
  - core
  - client
  - dashboard-visualiser-jsreport

customPackages:
  - id: custom-package-test
    path: "git@github.com:jembi/custom-package-test.git"
  - id: custom-local-package
    path: ./features/custom-local-package

profiles:
  - name: test-dev
    packages:
      - core
      - client
    envFiles:
      - ./features/test-conf/.env.test
    dev: true

  - name: test-custom-package
    packages:
      - custom-package-test
    envFiles:
      - ./features/test-conf/.env.test
    dev: false

  - name: test-mixed-package
    packages:
      - core
      - client
      - custom-package-test
    envFiles:
      - ./features/test-conf/.env.test
    dev: false

  - name: test-local-custom-package
    packages:
      - custom-local-package
    envFiles:
      - ./features/test-conf/.env.test
    dev: true
    
  - name: test-mixed-custom-package
    packages:
      - core
      - custom-package-test
      - custom-local-package
    envFiles:
      - ./features/test-conf/.env.test
    dev: true
