---
image: 'jembi/go-cli-test-image'
logPath: /tmp/logs

packages:
  - core
  - client

customPackages:
  - id: disi-on-platform
    path: "git@github.com:jembi/disi-on-platform.git"
    sshKey: ./id_rsa
    sshPassword: ./id_rsa_password.txt
  - id: cares-on-platform
    path: ./features/cares-on-platform
    sshKey: ./id_rsa
    sshPassword: ./id_rsa_password.txt

profiles:
  - name: dev
    packages:
      - core
      - client
    envFiles:
      - ./features/test-conf/.env.test
    dev: true

  - name: custom-package
    packages:
      - disi-on-platform
    envFiles:
      - ./features/test-conf/.env.test
    dev: false

  - name: mixed-package
    packages:
      - core
      - client
      - disi-on-platform
    envFiles:
      - ./features/test-conf/.env.test
    dev: false

  - name: local-custom-package
    packages:
      - cares-on-platform
    envFiles:
      - ./features/test-conf/.env.test
    dev: true
    
  - name: mixed-custom-package
    packages:
      - core
      - disi-on-platform
      - cares-on-platform
    envFiles:
      - ./features/test-conf/.env.test
    dev: true
