paths:
  /composeupcoredod:
    get:
      description: Runs `docker run /var/run/docker.sock:/var/run/docker.sock openhie/instant:latest init -t docker core`
      operationId: ComposeUpCoreDOD
      summary: Launches docker DooD container and runs core package.
      tags:
      - docker
  /debugdocker:
    get:
      description: Runs equivalent of a `docker ps` command to ensure Docker is running and installed locally.
      operationId: debugDocker
      summary: Confirms Docker is running.
      tags:
      - docker
  /debugkubernetes:
    get:
      description: Runs equivalent of a `kubectl config view` command to ensure kubectl is installed and configured.
      operationId: DebugKubernetes
      summary: Confirms Kubernetes is running.
      tags:
      - kubernetes
  /disclaimer:
    get:
      description: Adds accept_disclaimer file in `$HOME/.instant/` Avoids visiting the disclaimer page.
      operationId: Disclaimer
      summary: Adds a disclaimer to the local repository.
      tags:
      - admin
  /events:
    get:
      description: Implements unidirectional streaming of console and stdout events for debugging.
      operationId: repoList
      summary: Stream of console events and stdout
      tags:
      - admin
  /setup:
    get:
      description: Clones or updates Instant GitHub repo in `$HOME/.instant` Does not require git to be installed.
      operationId: Setup
      summary: Clones or updates local Instant repository.
      tags:
      - admin
swagger: "2.0"
