---
image: 'jembi/go-cli-test-image'
logPath: /tmp/logs

packages:
  - client

profiles:
  - name: bad-env-file-path
    packages:
      - client
    envFiles:
      - ../test-conf/.env.none

  - name: dev
    packages:
      - dashboard-visualiser-jsreport
      - disi-on-platform
    envFiles:
      - ../test-conf/.env.test
    dev: true

  - name: only
    packages:
      - dashboard-visualiser-jsreport
      - disi-on-platform
      - core
    envFiles:
      - ../test-conf/.env.test
    only: true

  - name: dev-and-only
    packages:
      - core
    envFiles:
      - ../test-conf/.env.test
    dev: true
    only: true
