---
image: 'jembi/go-cli-test-image'
logPath: /tmp/logs

packages:
  - id: client
    name: OpenCR Client Registry

customPackages:
  - id: custom-package-1
    path: "path-to-1"
    sshKey: id_rsa
    sshPassword: id_rsa_password.txt

  - id: custom-package-2
    path: "path-to-2"
    sshKey: id_rsa
    sshPassword: id_rsa_password.txt

  - id: custom-package-2
    path: "path-to-2"
    sshKey: id_rsa
    sshPassword: id_rsa_password.txt

profiles:
  - name: dev
    packages:
      - id: disi-on-platform
        name: Disi On Platform
    envFiles:
      - ../test-conf/.env.test
    dev: true
