---
image: 'jembi/go-cli-test-image'
logPath: /tmp/logs

packages:
  - client

customPackages:
  - id: custom-package-1
    path: "path-to-1"

profiles:
  - name: dev
    packages:
      - cares-on-platform
    envFiles:
      - ../test-conf/.env.test
    dev: true
