---
image: 'jembi/go-cli-test-image'
logPath: /tmp/logs

packages:
  - client
  - dashboard-visualiser-jsreport

customPackages:
  - id: disi-on-platform
    path: "git@github.com:jembi/disi-on-platform.git"

profiles:
  - name: non-dev
    packages:
      - dashboard-visualiser-jsreport
      - disi-on-platform
    envFiles:
      - ../test-conf/.env.test

  - name: non-only
    packages:
      - dashboard-visualiser-jsreport
    envFiles:
      - ../test-conf/.env.one
      - ../test-conf/.env.two
