name: Create and release go-cli binaries for current and latest tags

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Build go-cli binary releases
      run:  cd ./ohiecli && ./buildreleases.sh

    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: ./ohiecli/bin/gocli-linux,./ohiecli/bin/gocli-macos,./ohiecli/bin/gocli.exe
        tag: latest
        commit: main

    - name: Release binaries to referenced tag
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./ohiecli/bin/gocli-linux
          ./ohiecli/bin/gocli-macos
          ./ohiecli/bin/gocli.exe
