name: Create and release go binaries for linux, windows and mac

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Build Releases
      run:  cd ./ohiecli && ./buildreleases.sh

    - name: Test binaries
      run: cd ./ohiecli/bin && ./gocli-linux help

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./ohiecli/bin/gocli-linux
          ./ohiecli/bin/gocli-macos
          ./ohiecli/bin/gocli.exe
