name: Create and release go binaries for linux, windows and mac

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build Releases
      run:  cd ./cli && ./buildreleases.sh

    - name: Test binaries
      run: cd ./cli/bin && ./gocli-linux help

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./cli/bin/gocli-linux
          ./cli/bin/gocli-macos
          ./cli/bin/gocli.exe
